### ISSUE TITLE
It would be nice to have support of Maps

### ISSUE THREAD

**Issue by aliubimov** [davidmarquis/fluent-interface-proxy#5]
It would be nice to have support of populating maps as well. I am not sure what API should be for this. 
For lists "having" is perfect, may be something like

```
aPerson.havingDetails("age", 25)
```

where person has property

```
private Map<String, Integer> details;
```

**Comment by davidmarquis** [comment]
Yes that could be possible. Have you tried to give this a shot and submit a pull request?

**Comment by aliubimov** [comment]
I didn't have a chance to create pull request. Let me work out this.

**Comment by davidmarquis** [comment]
After giving this further thoughts, you'd be better off using a Map builder for this. You could create your own implementation of a Map builder quickly.

My latest commit (https://github.com/davidmarquis/fluent-interface-proxy/commit/b033243cbcc9e0f331a954f347d1a26e05574040) introduces a `MapBuilder` and it will be available in the next release. If you need it, let me know!
