### ISSUE TITLE
BestMatchingConstructor#typesAreCompatible does type compatibility the opposite way

### ISSUE THREAD

**Issue by rahulpilani** [davidmarquis/fluent-interface-proxy#9]
On line 124 of BestMatchingConstructor.java, you have the following code:
`
                if (!inputParamType.isAssignableFrom(constructorParamType)) {
                    matches = false;
                    break;
                }
`

Shouldn't this comparison be the other way? like so:
`                if (!constructorParamType.isAssignableFrom(inputParamType)) {
                    matches = false;
                    break;
                }
`
It's perfectly fine if the constructor param is a super class or an interface of the inputType, but the other way around will be a compile error. So the net effect of this is that only exact types are allowed, for which there is no work-around if the constructor param is an interface.

**Comment by rahulpilani** [comment]
#10

**Comment by davidmarquis** [comment]
Thanks! Good catch! Merging to master... do you need this quickly? If yes I can release a new revision, otherwise I'll wait for the next release.

**Comment by rahulpilani** [comment]
How far out is the next release? For now I am avoiding using it because of this issue, so I am not blocked.

**Comment by davidmarquis** [comment]
I have released 2.1.2 with your fix, enjoy!

**Comment by rahulpilani** [comment]
Awesome! thanks!
